#pragma once

// Common
#define TWIST_FEEDBACK_PIN_DEFAULT 26
#define VALVE_SERVO_PIN_DEFAULT 25
#define TWIST_SERVO_PIN_DEFAULT 27
#define SQUEEZE_PIN_DEFAULT 17
#define VIBE0_PIN_DEFAULT 18
#define VIBE1_PIN_DEFAULT 19
#define VIBE2_PIN_DEFAULT 23
#define VIBE3_PIN_DEFAULT 32
#define CASE_FAN_PIN_DEFAULT 16
#define LUBE_BUTTON_PIN_DEFAULT 35
#define INTERNAL_TEMP_PIN_DEFAULT 34
#define DISPLAY_RST_PIN_DEFAULT -1
#define TEMP_PIN_DEFAULT 5
#define HEATER_PIN_DEFAULT 33
#define I2C_SDA_PIN_DEFAULT 21
#define I2C_SCL_PIN_DEFAULT 22
#define BUTTON_SET_PINS_DEFAULT {}// Arrays dont work like this. See Settingsfactory::loadDefaultVector for defaults workaround
#define BUTTON_SET_PINS_1 39
#define BUTTON_SET_PINS_2 -1
#define BUTTON_SET_PINS_3 -1
#define BUTTON_SET_PINS_4 -1

// OSR
#define PITCH_LEFT_SERVO_PIN_DEFAULT 4
#define RIGHT_SERVO_PIN_DEFAULT 13
#define LEFT_SERVO_PIN_DEFAULT 15

// SR6
#define PITCH_RIGHTSERVO_PIN_DEFAULT 14
#define RIGHT_UPPER_SERVO_PIN_DEFAULT 12
#define LEFT_UPPER_SERVO_PIN_DEFAULT 2

// BLDC (SSR1)
#define BLDC_ENCODER_PIN_DEFAULT 33
#define BLDC_CHIPSELECT_PIN_DEFAULT 5
#define BLDC_ENABLE_PIN_DEFAULT 14
#define BLDC_HALLEFFECT_PIN_DEFAULT 35
#define BLDC_PWMCHANNEL1_PIN_DEFAULT 27
#define BLDC_PWMCHANNEL2_PIN_DEFAULT 26
#define BLDC_PWMCHANNEL3_PIN_DEFAULT 25