#pragma once
// Setting defaults
#define SSID_DEFAULT_DEFAULT "YOUR SSID HERE"
#define WIFI_PASS_DEFAULT "YOUR PASSWORD HERE"
#define BOARD_TYPE_DEFAULT 0
#define LOG_LEVEL_DEFAULT 2
#define FULL_BUILD_DEFAULT false
#define TCODE_VERSION_DEFAULT (int)TCodeVersion::v0_3 // V0.3
#define UDP_SERVER_PORT_DEFAULT 8000
#define WEBSERVER_PORT_DEFAULT 80
#define HOST_NAME_DEFAULT "tcode"
#define FRIENDLY_NAME_DEFAULT "ESP32 TCode"
#define BLUETOOTH_ENABLED_DEFAULT false
#define PITCH_FREQUENCY_IS_DIFFERENT_DEFAULT false
#define MS_PER_RAD_DEFAULT 637
#define SERVO_FREQUENCY_DEFAULT 50
#define PITCH_FREQUENCY_DEFAULT 50
#define VALVE_FREQUENCY_DEFAULT 50
#define TWIST_FREQUENCY_DEFAULT 50
#define SQUEEZE_FREQUENCY_DEFAULT 50
#define CONTINUOUS_TWIST_DEFAULT false
#define FEEDBACK_TWIST_DEFAULT false
#define ANALOG_TWIST_DEFAULT false

#define BLDC_USEPWM_DEFAULT false
#define BLDC_USEMT6701_DEFAULT true
#define BLDC_USEHALLSENSOR_DEFAULT false
#define BLDC_PULLEY_CIRCUMFERENCE_DEFAULT 60
// See pin map for pins
#define BLDC_MOTORA_VOLTAGE_DEFAULT 20.0f
#define BLDC_MOTORA_CURRENT_DEFAULT 1.0f
#define BLDC_MOTORA_PARAMETERSKNOWN_DEFAULT false
#define BLDC_MOTORA_ZEROELECANGLE_DEFAULT 0.0f
#define BLDC_RAILLENGTH_DEFAULT 125
#define BLDC_STROKELENGTH_DEFAULT 120
#define STATICIP_DEFAULT false
#define LOCALIP_DEFAULT "192.168.0.150"
#define GATEWAY_DEFAULT "192.168.0.1"
#define SUBNET_DEFAULT "255.255.255.0"
#define DNS1_DEFAULT "8.8.8.8"
#define DNS2_DEFAULT "8.8.4.4"
#define SR6MODE_DEFAULT false
#define RIGHT_SERVO_ZERO_DEFAULT 1500
#define LEFT_SERVO_ZERO_DEFAULT 1500
#define RIGHT_UPPER_SERVO_ZERO_DEFAULT 1500
#define LEFT_UPPER_SERVO_ZERO_DEFAULT 1500
#define PITCH_LEFT_SERVO_ZERO_DEFAULT 1500
#define PITCH_RIGHT_SERVO_ZERO_DEFAULT 1500
#define TWIST_SERVO_ZERO_DEFAULT 1500
#define VALVE_SERVO_ZERO_DEFAULT 1500
#define SQUEEZE_ZERO_DEFAULT 1500
#define AUTO_VALVE_DEFAULT true
#define INVERSE_VALVE_DEFAULT false
#define VALVE_SERVO_90DEGREES_DEFAULT false
#define INVERSE_STROKE_DEFAULT false
#define INVERSE_PITCH_DEFAULT false
#define LUBE_AMOUNT_DEFAULT 255
#define LUBE_ENABLED_DEFAULT false
#define DISPLAY_ENABLED_DEFAULT true
#define SLEEVE_TEMP_DISPLAYED_DEFAULT false
#define VERSION_DISPLAYED_DEFAULT true
#define INTERNAL_TEMP_DISPLAYED_DEFAULT false
#define TEMP_SLEEVE_ENABLED_DEFAULT false
#define DISPLAY_SCREEN_WIDTH_DEFAULT 128
#define DISPLAY_SCREEN_HEIGHT_DEFAULT 64
#define TARGET_TEMP_DEFAULT 40.0f
#define HEAT_PWM_DEFAULT 255
#define HOLD_PWM_DEFAULT 110
#define DISPLAY_I2C_ADDRESS_DEFAULT "0x3c"
// #define DISPLAY_RST_PIN_DEFAULT -1
// #define TEMP_PIN_DEFAULT 5
// #define HEATER_PIN_DEFAULT 33
#define HEATER_THRESHOLD_DEFAULT 5.0f
#define HEATER_RESOLUTION_DEFAULT 8
#define HEATER_FREQUENCY_DEFAULT 50
#define FAN_CONTROL_ENABLED_DEFAULT false
#define CASE_FAN_FREQUENCY_DEFAULT 25
#define CASE_FAN_RESOLUTION_DEFAULT 10
#define INTERNAL_TEMP_FOR_FAN_DEFAULT 30.0
#define INTERNAL_MAX_TEMP_DEFAULT 50.0
#define TEMP_INTERNAL_ENABLED_DEFAULT false
#define BATTERY_LEVEL_ENABLED_DEFAULT false
#define BATTERY_LEVEL_NUMERIC_DEFAULT 0
#define BATTERY_VOLTAGE_MAX_DEFAULT 12.6
#define BATTERY_CAPACITY_MAX_DEFAULT 3500
#define VOICE_ENABLED_DEFAULT false
#define VOICE_MUTED_DEFAULT false
#define VOICE_WAKE_TIME_DEFAULT 10
#define VOICE_VOLUME_DEFAULT 0
#define LOG_INCLUDETAGS_DEFAULT {}
#define LOG_EXCLUDETAGS_DEFAULT {}

#define SSID_SETTING "ssid"
#define WIFI_PASS_SETTING "wifiPass"
#define BOARD_TYPE_SETTING "boardType"
#define LOG_LEVEL_SETTING "logLevel"
#define FULL_BUILD "fullBuild"
#define TCODE_VERSION_SETTING "TCodeVersion"
#define UDP_SERVER_PORT "udpServerPort"
#define WEBSERVER_PORT "webServerPort"
#define HOST_NAME "hostname"
#define FRIENDLY_NAME "friendlyName"
#define BLUETOOTH_ENABLED "bluetoothEnabled"
#define PITCH_FREQUENCY_IS_DIFFERENT "pitchFrequencyIsDifferent"
#define MS_PER_RAD "msPerRad"
#define SERVO_FREQUENCY "servoFrequency"
#define PITCH_FREQUENCY "pitchFrequency"
#define VALVE_FREQUENCY "valveFrequency"
#define TWIST_FREQUENCY "twistFrequency"
#define SQUEEZE_FREQUENCY "squeezeFrequency"
#define CONTINUOUS_TWIST "continuousTwist"
#define FEEDBACK_TWIST "feedbackTwist"
#define ANALOG_TWIST "analogTwist"
#define TWIST_FEEDBACK_PIN "TwistFeedBack_PIN"
#define RIGHT_SERVO_PIN "RightServo_PIN"
#define LEFT_SERVO_PIN "LeftServo_PIN"
#define RIGHT_UPPER_SERVO_PIN "RightUpperServo_PIN"
#define LEFT_UPPER_SERVO_PIN "LeftUpperServo_PIN"
#define PITCH_LEFT_SERVO_PIN "PitchLeftServo_PIN"
#define PITCH_RIGHTSERVO_PIN "PitchRightServo_PIN"
#define VALVE_SERVO_PIN "ValveServo_PIN"
#define TWIST_SERVO_PIN "TwistServo_PIN"
#define SQUEEZE_PIN "Squeeze_PIN"
#define VIBE0_PIN "Vibe0_PIN"
#define VIBE1_PIN "Vibe1_PIN"
#define VIBE2_PIN "Vibe2_PIN"
#define VIBE3_PIN "Vibe3_PIN"
#define CASE_FAN_PIN "Case_Fan_PIN"
#define LUBE_BUTTON_PIN "LubeButton_PIN"
#define INTERNAL_TEMP_PIN "Internal_Temp_PIN"
#define BLDC_USEPWM "BLDC_UsePWM"
#define BLDC_USEMT6701 "BLDC_UseMT6701"
#define BLDC_USEHALLSENSOR "BLDC_UseHallSensor"
#define BLDC_PULLEY_CIRCUMFERENCE "BLDC_Pulley_Circumference"
#define BLDC_ENCODER_PIN "BLDC_Encoder_PIN"
#define BLDC_CHIPSELECT_PIN "BLDC_ChipSelect_PIN"
#define BLDC_ENABLE_PIN "BLDC_Enable_PIN"
#define BLDC_HALLEFFECT_PIN "BLDC_HallEffect_PIN"
#define BLDC_PWMCHANNEL1_PIN "BLDC_PWMchannel1_PIN"
#define BLDC_PWMCHANNEL2_PIN "BLDC_PWMchannel2_PIN"
#define BLDC_PWMCHANNEL3_PIN "BLDC_PWMchannel3_PIN"
#define BLDC_MOTORA_VOLTAGE "BLDC_MotorA_Voltage"
#define BLDC_MOTORA_CURRENT "BLDC_MotorA_Current"
#define BLDC_MOTORA_PARAMETERSKNOWN "BLDC_MotorA_ParametersKnown"
#define BLDC_MOTORA_ZEROELECANGLE "BLDC_MotorA_ZeroElecAngle"
#define BLDC_RAILLENGTH "BLDC_RailLength"
#define BLDC_STROKELENGTH "BLDC_StrokeLength"
#define STATICIP "staticIP"
#define LOCALIP "localIP"
#define GATEWAY "gateway"
#define SUBNET "subnet"
#define DNS1 "dns1"
#define DNS2 "dns2"
#define SR6MODE "sr6Mode"
#define RIGHT_SERVO_ZERO "RightServo_ZERO"
#define LEFT_SERVO_ZERO "LeftServo_ZERO"
#define RIGHT_UPPER_SERVO_ZERO "RightUpperServo_ZERO"
#define LEFT_UPPE_RSERVO_ZERO "LeftUpperServo_ZERO"
#define PITCH_LEFT_SERVO_ZERO "PitchLeftServo_ZERO"
#define PITCH_RIGHT_SERVO_ZERO "PitchRightServo_ZERO"
#define TWIST_SERVO_ZERO "TwistServo_ZERO"
#define VALVE_SERVO_ZERO "ValveServo_ZERO"
#define SQUEEZE_ZERO "Squeeze_ZERO"
#define AUTO_VALVE "autoValve"
#define INVERSE_VALVE "inverseValve"
#define VALVE_SERVO_90DEGREES "valveServo90Degrees"
#define INVERSE_STROKE "inverseStroke"
#define INVERSE_PITCH "inversePitch"
#define LUBE_AMOUNT "lubeAmount"
#define LUBE_ENABLED "lubeEnabled"
#define DISPLAY_ENABLED "displayEnabled"
#define SLEEVE_TEMP_DISPLAYED "sleeveTempDisplayed"
#define VERSION_DISPLAYED "versionDisplayed"
#define INTERNAL_TEMP_DISPLAYED "internalTempDisplayed"
#define TEMP_SLEEVE_ENABLED "tempSleeveEnabled"
#define DISPLAY_SCREEN_WIDTH "Display_Screen_Width"
#define DISPLAY_SCREEN_HEIGHT "Display_Screen_Height"
#define TARGET_TEMP "TargetTemp"
#define HEAT_PWM "HeatPWM"
#define HOLD_PWM "HoldPWM"
#define DISPLAY_I2C_ADDRESS "Display_I2C_Address"
#define DISPLAY_RST_PIN "Display_Rst_PIN"
#define TEMP_PIN "Temp_PIN"
#define HEATER_PIN "Heater_PIN"
#define HEATER_THRESHOLD "heaterThreshold"
#define HEATER_RESOLUTION "heaterResolution"
#define HEATER_FREQUENCY "heaterFrequency"
#define FAN_CONTROL_ENABLED "fanControlEnabled"
#define CASE_FAN_FREQUENCY "caseFanFrequency"
#define CASE_FAN_RESOLUTION "caseFanResolution"
#define INTERNAL_TEMP_FOR_FAN "internalTempForFan"
#define INTERNAL_MAX_TEMP "internalMaxTemp"
#define TEMP_INTERNAL_ENABLED "tempInternalEnabled"
#define BATTERY_LEVEL_ENABLED "batteryLevelEnabled"
#define BATTERY_LEVEL_NUMERIC "batteryLevelNumeric"
#define BATTERY_VOLTAGE_MAX "batteryVoltageMax"
#define BATTERY_CAPACITY_MAX "batteryCapacityMax"
#define VOICE_ENABLED "voiceEnabled"
#define VOICE_MUTED "voiceMuted"
#define VOICE_WAKE_TIME "voiceWakeTime"
#define VOICE_VOLUME "voiceVolume"
#define LOG_INCLUDETAGS "log-include-tags"
#define LOG_EXCLUDETAGS "log-exclude-tags"

#define BUTTON_SET_PIN "buttonSetPin"
#define I2C_SDA_PIN "i2cSdaPin"
#define I2C_SCL_PIN "i2cSclPin"

;