name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      # - name: Download external library
      #   run: |
      #     wget https://github.com/xxxajk/spi4teensy3/archive/master.zip -O /tmp/spi4teensy3.zip
      #     unzip /tmp/spi4teensy3.zip -d /tmp

      - name: Run PlatformIO
        run: pio ci --lib="." --lib="/tmp/esp32" --board=uno --board=esp32doit-devkit-v1 --board=esp32doit-devkit-v1-bldc
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
